import { ThemeProvider } from '@/components/theme/theme-provider';
import { TooltipProvider } from '@/components/ui/tooltip';
import { GeistSans } from 'geist/font/sans';

import HeaderNavigation from '@/components/project/navigation/header';
import type { Metadata } from 'next';
import NextAuthProvider from '@/components/project/account/next-auth/session-provider';

import './globals.css';

export const metadata: Metadata = {
  title: 'SmartCript - Home',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={`${GeistSans.className}`}>
        <NextAuthProvider>
          <TooltipProvider>
            <ThemeProvider
              attribute="class"
              enableSystem
            >
              <HeaderNavigation />
              {children}
            </ThemeProvider>
          </TooltipProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
